### ISSUE TITLE
Use official Api

### ISSUE THREAD

**Issue by rafael1209** [yawaflua/tzeva-adom#1]
https://www.oref.org.il/warningMessages/alert/Alerts.json

https://alerts-history.oref.org.il/Shared/Ajax/GetDistricts.aspx?lang=he [Russain](https://alerts-history.oref.org.il/Shared/Ajax/GetDistricts.aspx?lang=ru) [English](https://alerts-history.oref.org.il/Shared/Ajax/GetDistricts.aspx?lang=en) [Arabic](https://alerts-history.oref.org.il/Shared/Ajax/GetDistricts.aspx?lang=ar)

https://www.oref.org.il/warningMessages/alert/History/AlertsHistory.json

**Comment by yawaflua** [comment]
אני לא רוצה זה

**Comment by yawaflua** [comment]
Ok, i add it to next patch

**Comment by yawaflua** [comment]
Add in last patch.
